#pragma once
#include <cstddef>

namespace Offsets {
    namespace client_dll {
        constexpr std::ptrdiff_t dwCSGOInput = 0x1E3C150;
        constexpr std::ptrdiff_t dwEntityList = 0x1D13CE8;
        constexpr std::ptrdiff_t dwGameEntitySystem = 0x1FB89D0;
        constexpr std::ptrdiff_t dwGameEntitySystem_highestEntityIndex = 0x20F0;
        constexpr std::ptrdiff_t dwGameRules = 0x1E31410;
        constexpr std::ptrdiff_t dwGlobalVars = 0x1BE41C0;
        constexpr std::ptrdiff_t dwGlowManager = 0x1E2E2B8;
        constexpr std::ptrdiff_t dwLocalPlayerController = 0x1E1DC18;
        constexpr std::ptrdiff_t dwLocalPlayerPawn = 0x1BEEF28;
        constexpr std::ptrdiff_t dwPlantedC4 = 0x1E36BE8;
        constexpr std::ptrdiff_t dwPrediction = 0x1BEEE40;
        constexpr std::ptrdiff_t dwSensitivity = 0x1E2ED08;
        constexpr std::ptrdiff_t dwSensitivity_sensitivity = 0x50;
        constexpr std::ptrdiff_t dwViewAngles = 0x1E3C800;
        constexpr std::ptrdiff_t dwViewMatrix = 0x1E323D0;
        constexpr std::ptrdiff_t dwViewRender = 0x1E32F48;
        constexpr std::ptrdiff_t dwWeaponC4 = 0x1DCF190;
    }
    namespace CSkeletonInstance {
        constexpr std::ptrdiff_t m_modelState = 0x190; // CModelState
        constexpr std::ptrdiff_t m_bIsAnimationEnabled = 0x490; // bool
        constexpr std::ptrdiff_t m_bUseParentRenderBounds = 0x491; // bool
        constexpr std::ptrdiff_t m_bDisableSolidCollisionsForHierarchy = 0x492; // bool
        constexpr std::ptrdiff_t m_bDirtyMotionType = 0x0; // bitfield:1
        constexpr std::ptrdiff_t m_bIsGeneratingLatchedParentSpaceState = 0x0; // bitfield:1
        constexpr std::ptrdiff_t m_materialGroup = 0x494; // CUtlStringToken
        constexpr std::ptrdiff_t m_nHitboxSet = 0x498; // uint8
    }
    namespace C_BaseEntity {
        constexpr std::ptrdiff_t m_CBodyComponent = 0x38; // CBodyComponent*
        constexpr std::ptrdiff_t m_NetworkTransmitComponent = 0x40; // CNetworkTransmitComponent
        constexpr std::ptrdiff_t m_nLastThinkTick = 0x328; // GameTick_t
        constexpr std::ptrdiff_t m_pGameSceneNode = 0x330; // CGameSceneNode*
        constexpr std::ptrdiff_t m_pRenderComponent = 0x338; // CRenderComponent*
        constexpr std::ptrdiff_t m_pCollision = 0x340; // CCollisionProperty*
        constexpr std::ptrdiff_t m_iMaxHealth = 0x348; // int32
        constexpr std::ptrdiff_t m_iHealth = 0x34C; // int32
        constexpr std::ptrdiff_t m_flDamageAccumulator = 0x350; // float32
        constexpr std::ptrdiff_t m_lifeState = 0x354; // uint8
        constexpr std::ptrdiff_t m_bTakesDamage = 0x355; // bool
        constexpr std::ptrdiff_t m_nTakeDamageFlags = 0x358; // TakeDamageFlags_t
        constexpr std::ptrdiff_t m_nPlatformType = 0x360; // EntityPlatformTypes_t
        constexpr std::ptrdiff_t m_ubInterpolationFrame = 0x361; // uint8
        constexpr std::ptrdiff_t m_hSceneObjectController = 0x364; // CHandle<C_BaseEntity>
        constexpr std::ptrdiff_t m_nNoInterpolationTick = 0x368; // int32
        constexpr std::ptrdiff_t m_nVisibilityNoInterpolationTick = 0x36C; // int32
        constexpr std::ptrdiff_t m_flProxyRandomValue = 0x370; // float32
        constexpr std::ptrdiff_t m_iEFlags = 0x374; // int32
        constexpr std::ptrdiff_t m_nWaterType = 0x378; // uint8
        constexpr std::ptrdiff_t m_bInterpolateEvenWithNoModel = 0x379; // bool
        constexpr std::ptrdiff_t m_bPredictionEligible = 0x37A; // bool
        constexpr std::ptrdiff_t m_bApplyLayerMatchIDToModel = 0x37B; // bool
        constexpr std::ptrdiff_t m_tokLayerMatchID = 0x37C; // CUtlStringToken
        constexpr std::ptrdiff_t m_nSubclassID = 0x380; // CUtlStringToken
        constexpr std::ptrdiff_t m_nSimulationTick = 0x390; // int32
        constexpr std::ptrdiff_t m_iCurrentThinkContext = 0x394; // int32
        constexpr std::ptrdiff_t m_aThinkFunctions = 0x398; // CUtlVector<thinkfunc_t>
        constexpr std::ptrdiff_t m_bDisabledContextThinks = 0x3B0; // bool
        constexpr std::ptrdiff_t m_flAnimTime = 0x3B4; // float32
        constexpr std::ptrdiff_t m_flSimulationTime = 0x3B8; // float32
        constexpr std::ptrdiff_t m_nSceneObjectOverrideFlags = 0x3BC; // uint8
        constexpr std::ptrdiff_t m_bHasSuccessfullyInterpolated = 0x3BD; // bool
        constexpr std::ptrdiff_t m_bHasAddedVarsToInterpolation = 0x3BE; // bool
        constexpr std::ptrdiff_t m_bRenderEvenWhenNotSuccessfullyInterpolated = 0x3BF; // bool
        constexpr std::ptrdiff_t m_nInterpolationLatchDirtyFlags = 0x3C0; // int32[2]
        constexpr std::ptrdiff_t m_ListEntry = 0x3C8; // uint16[11]
        constexpr std::ptrdiff_t m_flCreateTime = 0x3E0; // GameTime_t
        constexpr std::ptrdiff_t m_flSpeed = 0x3E4; // float32
        constexpr std::ptrdiff_t m_EntClientFlags = 0x3E8; // uint16
        constexpr std::ptrdiff_t m_bClientSideRagdoll = 0x3EA; // bool
        constexpr std::ptrdiff_t m_iTeamNum = 0x3EB; // uint8
        constexpr std::ptrdiff_t m_spawnflags = 0x3EC; // uint32
        constexpr std::ptrdiff_t m_nNextThinkTick = 0x3F0; // GameTick_t
        constexpr std::ptrdiff_t m_fFlags = 0x3F8; // uint32
        constexpr std::ptrdiff_t m_vecAbsVelocity = 0x3FC; // Vector
        constexpr std::ptrdiff_t m_vecServerVelocity = 0x408; // CNetworkVelocityVector
        constexpr std::ptrdiff_t m_vecVelocity = 0x430; // CNetworkVelocityVector
        constexpr std::ptrdiff_t m_vecBaseVelocity = 0x510; // Vector
        constexpr std::ptrdiff_t m_hEffectEntity = 0x51C; // CHandle<C_BaseEntity>
        constexpr std::ptrdiff_t m_hOwnerEntity = 0x520; // CHandle<C_BaseEntity>
        constexpr std::ptrdiff_t m_MoveCollide = 0x524; // MoveCollide_t
        constexpr std::ptrdiff_t m_MoveType = 0x525; // MoveType_t
        constexpr std::ptrdiff_t m_nActualMoveType = 0x526; // MoveType_t
        constexpr std::ptrdiff_t m_flWaterLevel = 0x528; // float32
        constexpr std::ptrdiff_t m_fEffects = 0x52C; // uint32
        constexpr std::ptrdiff_t m_hGroundEntity = 0x530; // CHandle<C_BaseEntity>
        constexpr std::ptrdiff_t m_nGroundBodyIndex = 0x534; // int32
        constexpr std::ptrdiff_t m_flFriction = 0x538; // float32
        constexpr std::ptrdiff_t m_flElasticity = 0x53C; // float32
        constexpr std::ptrdiff_t m_flGravityScale = 0x540; // float32
        constexpr std::ptrdiff_t m_flTimeScale = 0x544; // float32
        constexpr std::ptrdiff_t m_bAnimatedEveryTick = 0x548; // bool
        constexpr std::ptrdiff_t m_bGravityDisabled = 0x549; // bool
        constexpr std::ptrdiff_t m_flNavIgnoreUntilTime = 0x54C; // GameTime_t
        constexpr std::ptrdiff_t m_hThink = 0x550; // uint16
        constexpr std::ptrdiff_t m_fBBoxVisFlags = 0x560; // uint8
        constexpr std::ptrdiff_t m_flActualGravityScale = 0x564; // float32
        constexpr std::ptrdiff_t m_bGravityActuallyDisabled = 0x568; // bool
        constexpr std::ptrdiff_t m_bPredictable = 0x569; // bool
        constexpr std::ptrdiff_t m_bRenderWithViewModels = 0x56A; // bool
        constexpr std::ptrdiff_t m_nFirstPredictableCommand = 0x56C; // int32
        constexpr std::ptrdiff_t m_nLastPredictableCommand = 0x570; // int32
        constexpr std::ptrdiff_t m_hOldMoveParent = 0x574; // CHandle<C_BaseEntity>
        constexpr std::ptrdiff_t m_Particles = 0x578; // CParticleProperty
        constexpr std::ptrdiff_t m_vecAngVelocity = 0x5A8; // QAngle
        constexpr std::ptrdiff_t m_DataChangeEventRef = 0x5B4; // int32
        constexpr std::ptrdiff_t m_dependencies = 0x5B8; // CUtlVector<CEntityHandle>
        constexpr std::ptrdiff_t m_nCreationTick = 0x5D0; // int32
        constexpr std::ptrdiff_t m_bAnimTimeChanged = 0x5DD; // bool
        constexpr std::ptrdiff_t m_bSimulationTimeChanged = 0x5DE; // bool
        constexpr std::ptrdiff_t m_sUniqueHammerID = 0x5E8; // CUtlString
        constexpr std::ptrdiff_t m_nBloodType = 0x5F0; // BloodType
    }
    namespace CCSPlayerController {
        constexpr std::ptrdiff_t m_pInGameMoneyServices = 0x7F8; // CCSPlayerController_InGameMoneyServices*
        constexpr std::ptrdiff_t m_pInventoryServices = 0x800; // CCSPlayerController_InventoryServices*
        constexpr std::ptrdiff_t m_pActionTrackingServices = 0x808; // CCSPlayerController_ActionTrackingServices*
        constexpr std::ptrdiff_t m_pDamageServices = 0x810; // CCSPlayerController_DamageServices*
        constexpr std::ptrdiff_t m_iPing = 0x818; // uint32
        constexpr std::ptrdiff_t m_bHasCommunicationAbuseMute = 0x81C; // bool
        constexpr std::ptrdiff_t m_uiCommunicationMuteFlags = 0x820; // uint32
        constexpr std::ptrdiff_t m_szCrosshairCodes = 0x828; // CUtlSymbolLarge
        constexpr std::ptrdiff_t m_iPendingTeamNum = 0x830; // uint8
        constexpr std::ptrdiff_t m_flForceTeamTime = 0x834; // GameTime_t
        constexpr std::ptrdiff_t m_iCompTeammateColor = 0x838; // int32
        constexpr std::ptrdiff_t m_bEverPlayedOnTeam = 0x83C; // bool
        constexpr std::ptrdiff_t m_flPreviousForceJoinTeamTime = 0x840; // GameTime_t
        constexpr std::ptrdiff_t m_szClan = 0x848; // CUtlSymbolLarge
        constexpr std::ptrdiff_t m_sSanitizedPlayerName = 0x850; // CUtlString
        constexpr std::ptrdiff_t m_iCoachingTeam = 0x858; // int32
        constexpr std::ptrdiff_t m_nPlayerDominated = 0x860; // uint64
        constexpr std::ptrdiff_t m_nPlayerDominatingMe = 0x868; // uint64
        constexpr std::ptrdiff_t m_iCompetitiveRanking = 0x870; // int32
        constexpr std::ptrdiff_t m_iCompetitiveWins = 0x874; // int32
        constexpr std::ptrdiff_t m_iCompetitiveRankType = 0x878; // int8
        constexpr std::ptrdiff_t m_iCompetitiveRankingPredicted_Win = 0x87C; // int32
        constexpr std::ptrdiff_t m_iCompetitiveRankingPredicted_Loss = 0x880; // int32
        constexpr std::ptrdiff_t m_iCompetitiveRankingPredicted_Tie = 0x884; // int32
        constexpr std::ptrdiff_t m_nEndMatchNextMapVote = 0x888; // int32
        constexpr std::ptrdiff_t m_unActiveQuestId = 0x88C; // uint16
        constexpr std::ptrdiff_t m_rtActiveMissionPeriod = 0x890; // uint32
        constexpr std::ptrdiff_t m_nQuestProgressReason = 0x894; // QuestProgress::Reason
        constexpr std::ptrdiff_t m_unPlayerTvControlFlags = 0x898; // uint32
        constexpr std::ptrdiff_t m_iDraftIndex = 0x8C8; // int32
        constexpr std::ptrdiff_t m_msQueuedModeDisconnectionTimestamp = 0x8CC; // uint32
        constexpr std::ptrdiff_t m_uiAbandonRecordedReason = 0x8D0; // uint32
        constexpr std::ptrdiff_t m_eNetworkDisconnectionReason = 0x8D4; // uint32
        constexpr std::ptrdiff_t m_bCannotBeKicked = 0x8D8; // bool
        constexpr std::ptrdiff_t m_bEverFullyConnected = 0x8D9; // bool
        constexpr std::ptrdiff_t m_bAbandonAllowsSurrender = 0x8DA; // bool
        constexpr std::ptrdiff_t m_bAbandonOffersInstantSurrender = 0x8DB; // bool
        constexpr std::ptrdiff_t m_bDisconnection1MinWarningPrinted = 0x8DC; // bool
        constexpr std::ptrdiff_t m_bScoreReported = 0x8DD; // bool
        constexpr std::ptrdiff_t m_nDisconnectionTick = 0x8E0; // int32
        constexpr std::ptrdiff_t m_bControllingBot = 0x8F0; // bool
        constexpr std::ptrdiff_t m_bHasControlledBotThisRound = 0x8F1; // bool
        constexpr std::ptrdiff_t m_bHasBeenControlledByPlayerThisRound = 0x8F2; // bool
        constexpr std::ptrdiff_t m_nBotsControlledThisRound = 0x8F4; // int32
        constexpr std::ptrdiff_t m_bCanControlObservedBot = 0x8F8; // bool
        constexpr std::ptrdiff_t m_hPlayerPawn = 0x8FC; // CHandle<C_CSPlayerPawn>
        constexpr std::ptrdiff_t m_hObserverPawn = 0x900; // CHandle<C_CSObserverPawn>
        constexpr std::ptrdiff_t m_bPawnIsAlive = 0x904; // bool
        constexpr std::ptrdiff_t m_iPawnHealth = 0x908; // uint32
        constexpr std::ptrdiff_t m_iPawnArmor = 0x90C; // int32
        constexpr std::ptrdiff_t m_bPawnHasDefuser = 0x910; // bool
        constexpr std::ptrdiff_t m_bPawnHasHelmet = 0x911; // bool
        constexpr std::ptrdiff_t m_nPawnCharacterDefIndex = 0x912; // uint16
        constexpr std::ptrdiff_t m_iPawnLifetimeStart = 0x914; // int32
        constexpr std::ptrdiff_t m_iPawnLifetimeEnd = 0x918; // int32
        constexpr std::ptrdiff_t m_iPawnBotDifficulty = 0x91C; // int32
        constexpr std::ptrdiff_t m_hOriginalControllerOfCurrentPawn = 0x920; // CHandle<CCSPlayerController>
        constexpr std::ptrdiff_t m_iScore = 0x924; // int32
        constexpr std::ptrdiff_t m_recentKillQueue = 0x928; // uint8[8]
        constexpr std::ptrdiff_t m_nFirstKill = 0x930; // uint8
        constexpr std::ptrdiff_t m_nKillCount = 0x931; // uint8
        constexpr std::ptrdiff_t m_bMvpNoMusic = 0x932; // bool
        constexpr std::ptrdiff_t m_eMvpReason = 0x934; // int32
        constexpr std::ptrdiff_t m_iMusicKitID = 0x938; // int32
        constexpr std::ptrdiff_t m_iMusicKitMVPs = 0x93C; // int32
        constexpr std::ptrdiff_t m_iMVPs = 0x940; // int32
        constexpr std::ptrdiff_t m_bIsPlayerNameDirty = 0x944; // bool
        constexpr std::ptrdiff_t m_bFireBulletsSeedSynchronized = 0x945; // bool
    }
    namespace CGameSceneNode {
        constexpr std::ptrdiff_t m_nodeToWorld = 0x10; // CTransformWS
        constexpr std::ptrdiff_t m_pOwner = 0x30; // CEntityInstance*
        constexpr std::ptrdiff_t m_pParent = 0x38; // CGameSceneNode*
        constexpr std::ptrdiff_t m_pChild = 0x40; // CGameSceneNode*
        constexpr std::ptrdiff_t m_pNextSibling = 0x48; // CGameSceneNode*
        constexpr std::ptrdiff_t m_hParent = 0x78; // CGameSceneNodeHandle
        constexpr std::ptrdiff_t m_vecOrigin = 0x88; // CNetworkOriginCellCoordQuantizedVector
        constexpr std::ptrdiff_t m_angRotation = 0xC0; // QAngle
        constexpr std::ptrdiff_t m_flScale = 0xCC; // float32
        constexpr std::ptrdiff_t m_vecAbsOrigin = 0xD0; // VectorWS
        constexpr std::ptrdiff_t m_angAbsRotation = 0xDC; // QAngle
        constexpr std::ptrdiff_t m_flAbsScale = 0xE8; // float32
        constexpr std::ptrdiff_t m_vecWrappedLocalOrigin = 0xEC; // Vector
        constexpr std::ptrdiff_t m_angWrappedLocalRotation = 0xF8; // QAngle
        constexpr std::ptrdiff_t m_flWrappedScale = 0x104; // float32
        constexpr std::ptrdiff_t m_nParentAttachmentOrBone = 0x108; // int16
        constexpr std::ptrdiff_t m_bDebugAbsOriginChanges = 0x10A; // bool
        constexpr std::ptrdiff_t m_bDormant = 0x10B; // bool
        constexpr std::ptrdiff_t m_bForceParentToBeNetworked = 0x10C; // bool
        constexpr std::ptrdiff_t m_bDirtyHierarchy = 0x0; // bitfield:1
        constexpr std::ptrdiff_t m_bDirtyBoneMergeInfo = 0x0; // bitfield:1
        constexpr std::ptrdiff_t m_bNetworkedPositionChanged = 0x0; // bitfield:1
        constexpr std::ptrdiff_t m_bNetworkedAnglesChanged = 0x0; // bitfield:1
        constexpr std::ptrdiff_t m_bNetworkedScaleChanged = 0x0; // bitfield:1
        constexpr std::ptrdiff_t m_bWillBeCallingPostDataUpdate = 0x0; // bitfield:1
        constexpr std::ptrdiff_t m_bBoneMergeFlex = 0x0; // bitfield:1
        constexpr std::ptrdiff_t m_nLatchAbsOrigin = 0x0; // bitfield:2
        constexpr std::ptrdiff_t m_bDirtyBoneMergeBoneToRoot = 0x0; // bitfield:1
        constexpr std::ptrdiff_t m_nHierarchicalDepth = 0x10F; // uint8
        constexpr std::ptrdiff_t m_nHierarchyType = 0x110; // uint8
        constexpr std::ptrdiff_t m_nDoNotSetAnimTimeInInvalidatePhysicsCount = 0x111; // uint8
        constexpr std::ptrdiff_t m_name = 0x114; // CUtlStringToken
        constexpr std::ptrdiff_t m_hierarchyAttachName = 0x158; // CUtlStringToken
        constexpr std::ptrdiff_t m_flZOffset = 0x15C; // float32
        constexpr std::ptrdiff_t m_flClientLocalScale = 0x160; // float32
        constexpr std::ptrdiff_t m_vRenderOrigin = 0x164; // Vector
    }
    namespace C_BasePlayerPawn {
        constexpr std::ptrdiff_t m_pWeaponServices = 0x13F0; // CPlayer_WeaponServices*
        constexpr std::ptrdiff_t m_pItemServices = 0x13F8; // CPlayer_ItemServices*
        constexpr std::ptrdiff_t m_pAutoaimServices = 0x1400; // CPlayer_AutoaimServices*
        constexpr std::ptrdiff_t m_pObserverServices = 0x1408; // CPlayer_ObserverServices*
        constexpr std::ptrdiff_t m_pWaterServices = 0x1410; // CPlayer_WaterServices*
        constexpr std::ptrdiff_t m_pUseServices = 0x1418; // CPlayer_UseServices*
        constexpr std::ptrdiff_t m_pFlashlightServices = 0x1420; // CPlayer_FlashlightServices*
        constexpr std::ptrdiff_t m_pCameraServices = 0x1428; // CPlayer_CameraServices*
        constexpr std::ptrdiff_t m_pMovementServices = 0x1430; // CPlayer_MovementServices*
        constexpr std::ptrdiff_t m_ServerViewAngleChanges = 0x1440; // C_UtlVectorEmbeddedNetworkVar<ViewAngleServerChange_t>
        constexpr std::ptrdiff_t v_angle = 0x14A8; // QAngle
        constexpr std::ptrdiff_t v_anglePrevious = 0x14B4; // QAngle
        constexpr std::ptrdiff_t m_iHideHUD = 0x14C0; // uint32
        constexpr std::ptrdiff_t m_skybox3d = 0x14C8; // sky3dparams_t
        constexpr std::ptrdiff_t m_flDeathTime = 0x1558; // GameTime_t
        constexpr std::ptrdiff_t m_vecPredictionError = 0x155C; // Vector
        constexpr std::ptrdiff_t m_flPredictionErrorTime = 0x1568; // GameTime_t
        constexpr std::ptrdiff_t m_vecLastCameraSetupLocalOrigin = 0x1588; // Vector
        constexpr std::ptrdiff_t m_flLastCameraSetupTime = 0x1594; // GameTime_t
        constexpr std::ptrdiff_t m_flFOVSensitivityAdjust = 0x1598; // float32
        constexpr std::ptrdiff_t m_flMouseSensitivity = 0x159C; // float32
        constexpr std::ptrdiff_t m_vOldOrigin = 0x15A0; // Vector
        constexpr std::ptrdiff_t m_flOldSimulationTime = 0x15AC; // float32
        constexpr std::ptrdiff_t m_nLastExecutedCommandNumber = 0x15B0; // int32
        constexpr std::ptrdiff_t m_nLastExecutedCommandTick = 0x15B4; // int32
        constexpr std::ptrdiff_t m_hController = 0x15B8; // CHandle<CBasePlayerController>
        constexpr std::ptrdiff_t m_hDefaultController = 0x15BC; // CHandle<CBasePlayerController>
        constexpr std::ptrdiff_t m_bIsSwappingToPredictableController = 0x15C0; // bool
    }
}

